### ISSUE TITLE
Icon Missing on home page

### ISSUE THREAD

**Issue by khawarr85** [ncosentino/DevLeader#4]
The devleader icon is not showing and does not align with other icons on the Home page.
![image](https://github.com/user-attachments/assets/f3aeccca-4db5-4a45-8725-535cd019db86)

**Comment by ncosentino** [comment]
My wordpress plugins do not have a Threads icon built in for the same theme -- I'll be rebuilding my entire site before I address this, most likely.

Thanks for reporting.
